update automating tests documentation
galasa-dev/galasa.dev pull request #402
Opened 2022-07-26 11:39 UTC by CaroMac

2022-09-14 10:55 UTC, hobbit1983 requested changes

2022-09-20 11:46 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/automating-overview.md
> +Galasa SimBank shows how you can run a Galasa test locally inside an IDE. Running a test inside an IDE enables test and application development teams to run tests in a local workspace that interacts
updated locally

2022-09-20 11:46 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/automating-overview.md
> +4. Run the test headlessly as part of a pipeline
updated locally

2022-09-20 11:47 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/automating-overview.md
> +Compiling and running a test locally in Eclipse automatically creates a test jar file and an OSGi Bundle Repository (OBR) which enable Galasa to run any artifacts that are contained within the worksp
updated locally

2022-09-20 11:48 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/automating-overview.md
> +1. Structure a test to [run in automation](/docs/ecosystem/automating)
update locally

2022-10-20 14:45 UTC, hobbit1983 approved these changes

2022-11-14 10:35 UTC, CaroMac commented
This issue is for the review / update / approve part of the work. I have some questions / thoughts on these docs so I will use the review issue to go through these as it makes sense to do it as part of that piece of work. Links are here:
https://deploy-preview-402--galasa.netlify.app/docs/writing-own-tests
https://deploy-preview-402--galasa.netlify.app/docs/ecosystem/automating/overview
https://deploy-preview-402--galasa.netlify.app/docs/writing-own-tests/setting-up-galasa-project
https://deploy-preview-402--galasa.netlify.app/docs/writing-own-tests/setting-up-galasa-project-outside
https://deploy-preview-402--galasa.netlify.app/docs/ecosystem/automating/running-automation
https://deploy-preview-402--galasa.netlify.app/docs/ecosystem/automating/deploying-to-maven
https://deploy-preview-402--galasa.netlify.app/docs/writing-own-tests/test-streams

2022-11-25 09:34 UTC, techcobweb commented on src/markdown-pages/docs/ecosystem/deploy-to-maven.md
> +    1. Update the details of the Nexus server for _id_, _username_, and _password_.
"Refer to the maven documentation for details of how to encrypt this password if required"

2023-02-22 14:21 UTC, closed without merging