Issue540 - helm documentation for installing an ecosystem on Kubernetes
galasa-dev/galasa.dev pull request #579
Opened 2023-02-09 14:09 UTC by CaroMac

2023-02-10 13:11 UTC, eamansour requested changes
Good work! Just needs a few changes that I've mentioned in the review comments - let me know if you need any help!

2023-02-10 14:40 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +The following sections explain how to install a Galasa Ecosystem on a Kubernetes cluster by using Helm and to validate that the ecosystem installed successfully.
made a change

2023-02-10 14:41 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +The <a href=https://github.com/galasa-dev/helm target="_blank"> Galasa Helm repository</a> contains the YAML that is referenced in the following sections.
updated

2023-02-10 14:41 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +- You must have administrator authority for Kubernetes.
ok, thank you. will remove.

2023-02-10 14:42 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +- <a href=https://helm.sh target="_blank"> Helm</a> must be installed to use the charts. See the <a href=https://helm.sh/docs/ target="_blank"> Helm documentation</a> to get started.
done

2023-02-10 14:44 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +When the `helm test` command ends and displays a success message, the Ecosystem is set up correctly and ready to be used.
ok

2023-02-10 14:45 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +If RBAC is active on your Kubernetes cluster,  you can assign the `galasa-admin` role to a user by replacing the <a href=https://github.com/galasa-dev/helm/blob/main/charts/ecosystem/rbac-admin.yaml#
thank you

2023-02-10 14:47 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +Alternatively, you can enter the bootstrap URL in the ```--bootstrap``` option of a `galasctl` command.
ah ok yes I understand. will do.

2023-02-10 14:55 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +kubectl apply -f rbac.yaml
thank you

2023-02-10 16:10 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +1. Edit the <a href=https://github.com/galasa-dev/helm/blob/main/charts/ecosystem/values.yaml target="_blank"> values.yaml</a> file:
added download

2023-02-10 16:12 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +1.	View the status of the deployed pods by running `kubectl get pods` in another terminal. The following services        displayed with a status of *Running*:
done

2023-02-10 16:21 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +	helm install <release-name> galasa/ecosystem –wait
thank you

2023-02-10 16:27 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +To enable users to interact with Helm charts, you must assign those users to the `galasa-admin` role. Users must have access to the cluster in order to be assigned to the `galasa-admin` role. This ro
thanks, updated

2023-02-10 16:40 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +For chart versions `0.23.0` and earlier, you must apply the <a href=https://github.com/galasa-dev/helm/blob/main/charts/ecosystem/templates/rbac.yaml target="_blank"> rbac.yaml</a> file manually by r
have added in explanation of the service account up front. I reworded the text to say that versions later than 0.23.0 it will be automatic

2023-02-13 14:13 UTC, eamansour requested changes
Good updates! Just spotted a few more minor corrections to make

2023-02-21 10:53 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +For chart versions `0.23.0` and earlier, you must apply the RBAC file manually by running the following command in the repository's <a href=https://github.com/galasa-dev/helm/tree/main/charts/ecosyst
done

2023-02-21 10:53 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +For chart versions later than `0.23.0`, the RBAC file is applied automatically when installing the ecosystem chart.
done

2023-02-21 10:54 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +    `<release-name>` is the name that you gave the ecosystem.<br><br>
done

2023-02-21 10:55 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-installing-k8s.md
> +1.	View the status of the deployed pods by running `kubectl get pods` in another terminal. The returned results look similar to the following example:
ok

2023-02-21 11:33 UTC, eamansour approved these changes

2023-02-21 13:35 UTC, merged