Release30
galasa-dev/galasa.dev pull request #710
Opened 2023-10-11 11:54 UTC by CaroMac

contains properties get / set / delete cmd and release notes

2023-10-11 12:26 UTC, KirbyKatcher submitted a review, later dismissed

2023-10-11 13:19 UTC, eamansour requested changes

2023-10-11 14:44 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-manage-cps.md
> +System administrators can use the CLI to set Ecosystem-wide configuration properties during Ecosystem installation.
yes I noticed some inconsistencies so I changed to Ecosystem in the revamp work so will stick with that. have changed during to after.

2023-10-11 14:45 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-manage-cps.md
> +The ability to retrieve, set, and delete properties held in the configuration properties store (CPS) directly into an Ecosystem by using the Galasa CLI makes it easier for testers to set parameters a
oh yes good idea. done.

2023-10-11 14:46 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-manage-cps.md
> +Use the `galasactl properties get` command to read CPS properties and values from a specified namespace in the Galasa Ecosystem to verify that the properties exist and are set correctly. You can filt
removed extra space

2023-10-11 14:47 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-manage-cps.md
> +framework test.batch2.stream  value2
Will change

2023-10-11 14:49 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-manage-cps.md
> +framework.test.stream.EXAMPLE.repo http://<your-maven-repo-hostname>/repository/maven
oh yes that is a good idea

2023-10-11 14:54 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-manage-cps.md
> +To filter the properties that are returned, without specifying the property name, use the `–prefix`, `–suffix`, and ``--infix`` flags. You can specify more than one `--infix` value by using a comma s
yes that is a good idea. will change it.

2023-10-11 15:05 UTC, CaroMac commented on src/markdown-pages/docs/ecosystem/ecosystem-manage-cps.md
> +framework test.batch2.stream  value2
have also updated the example showing the sort order of returned results

2023-10-13 13:20 UTC, eamansour approved these changes

2023-10-13 13:43 UTC, merged