Localmavenrepo
galasa-dev/galasa.dev pull request #731
Opened 2023-11-08 13:54 UTC by CaroMac

2023-11-08 14:41 UTC, KirbyKatcher requested changes

2023-11-08 14:41 UTC, KirbyKatcher commented on src/markdown-pages/docs/ecosystem/ecosystem-manage-cps.md
> +Values are masked in `secure` namespace types. All other namespaces are classed as `normal` type. Returned properties are sorted in alphabetical order.
I think we need to explain the difference between secure and normal a bit more here , i.e. secure namespace types will not display property values when queried (they are redacted)

2023-11-08 14:44 UTC, Wyvinar approved these changes
Looks good and makes sense I think, bar one comment about a link

2023-12-06 09:18 UTC, CaroMac commented
going to close this and raise two new PRs for each issue off the new doc base

2023-12-06 09:31 UTC, closed without merging